// type.js: song timing, typography, crisp 2D graphics and the text registry.
//
// Added for the interp music video; not part of the original ClaudeAnimationBase kit. The guide's "no text" rule is
// deliberately overridden here: the lyrics carry the jargon (singers blur "logit lens"), so text is a first-class layer.
//
// Everything is still a pure function of t. Text and 2D graphics are queued on LETTERS as Canvas2D draw ops, so they
// follow the kit's layering: they land on top of whatever the shot has painted so far, follow an active camera (pass
// {screen: true} to opt out), and flushLetters() before a wipe puts them under the wipe.
//
// Every piece of text drawn through tx() is recorded in TEXTREG with its on-screen box, so window.textCheck() can flag
// overlaps, text outside the title-safe area, text too small or too low-contrast to read, and reads that flash by.

// ---------- song timing (SONG comes from src/data/song*.js, generated by tools/song_js.py) ----------
const HAS_SONG = typeof SONG !== 'undefined';
const barN = t => Math.floor(bpOf(t) / 4);                     // bar index (bar 0 starts at the first downbeat)
const beatInBar = t => ((beatN(t) % 4) + 4) % 4;                // 0..3; 0 is the downbeat
const barFrac = t => frac(bpOf(t) / 4);                         // 0..1 progress through the current bar
const beatT = n => OFF + n * BEAT;                              // time of beat n
const barT = n => OFF + n * 4 * BEAT;                           // time of bar n's downbeat
// Index of the last element of a sorted array <= x (or -1). Used on event-time lists.
function lastLE(arr, x, key = v => v) { let lo = 0, hi = arr.length - 1, r = -1; while (lo <= hi) { const m = (lo + hi) >> 1; if (key(arr[m]) <= x) { r = m; lo = m + 1; } else hi = m - 1; } return r; }
// 1 at each event time in `times` (sorted), decaying after it: pulse() for arbitrary events (word onsets, hits).
function hitPulse(t, times, k = 8) { const i = lastLE(times, t); return i < 0 ? 0 : Math.exp(-(t - times[i]) * k); }
// The SONG line being sung at t, or null. hold: seconds a line stays "current" after its last word ends; early: seconds
// before its first word it becomes current (subtitle preview: 4-6 frames early and dim, per refs/video_craft.md §2.2).
function lineAt(t, hold = .25, early = 0) {
  if (!HAS_SONG) return null;
  const L = SONG.lines.filter(l => l.t0 != null), i = lastLE(L, t + early, l => l.t0);
  if (i < 0) return null;
  const l = L[i]; return t <= l.t1 + hold ? l : null;
}
const lineByIdx = i => HAS_SONG ? SONG.lines.find(l => l.i === i) : null;
function sectionAt(t) { if (!HAS_SONG) return null; const i = lastLE(SONG.sections, t, s => s.t0); return i < 0 ? null : SONG.sections[i]; }
// The display word being sung at t within a line (index), or -1 before the first word.
const wordIdxAt = (line, t) => lastLE(line.words, t, w => w.t0 ?? Infinity);
// Loudness 0..1 at t (10 Hz RMS, normalised to the song's 98th percentile) for audio-reactive motion.
let _rmsMax = null;
function loud(t) {
  if (!HAS_SONG) return 0;
  if (_rmsMax == null) { const s = [...SONG.rms10].sort((a, b) => a - b); _rmsMax = s[Math.floor(s.length * .98)] || 1; }
  const x = t * 10, i = Math.floor(x), a = SONG.rms10[i] ?? 0, b = SONG.rms10[i + 1] ?? a;
  return clamp(lerp(a, b, x - i) / _rmsMax);
}

// ---------- fonts (vendored in assets/fonts, all SIL OFL 1.1; see tools/fetch_fonts.py) ----------
const FONT = {
  marker: 'Permanent Marker', hanSans: 'Black Han Sans', dela: 'Dela Gothic One', bagel: 'Bagel Fat One', anton: 'Anton',
  archivoBlack: 'Archivo Black', archivo: 'Archivo', bricolage: 'Bricolage Grotesque', unbounded: 'Unbounded',
  shoulders: 'Big Shoulders Display', syne: 'Syne', rubikMono: 'Rubik Mono One', outfit: 'Outfit',
  instrument: 'Instrument Serif', newsreader: 'Newsreader', plexMono: 'IBM Plex Mono', jbMono: 'JetBrains Mono',
  dot: 'DotGothic16', silk: 'Silkscreen', vt: 'VT323', caveat: 'Caveat', gaegu: 'Gaegu',
  cmu: 'CMU Serif', cmuTT: 'CMU Typewriter', cmuSans: 'CMU Sans', fraunces: 'Fraunces', shantell: 'Shantell Sans',
};
async function loadFonts() {
  const specs = [];
  for (const fam of Object.values(FONT)) for (const st of ['normal', 'italic']) for (const wt of [300, 400, 500, 700, 900]) specs.push(`${st} ${wt} 100px "${fam}"`);
  specs.push('100px "Adobe Blank"', `100px "${FONT_FALLBACK}"`);
  await Promise.all(specs.map(s => document.fonts.load(s).catch(() => null)));
  await document.fonts.ready;
}
// Which FONT families have at least one face loaded (a missing one silently falls back to a system font).
window.fontStatus = () => { const ok = new Set([...document.fonts].filter(f => f.status === 'loaded').map(f => f.family.replace(/"/g, ''))); return Object.fromEntries(Object.entries(FONT).map(([k, f]) => [k, ok.has(f)])); };

// ---------- measuring ----------
const MEAS = document.createElement('canvas').getContext('2d');
const famOf = f => FONT[f] || f || FONT.marker;
// Every stack ends in Noto Sans Math, so arrows and maths symbols (→ ↓ ≈ ×), which the display faces lack, always come
// from one known face instead of whatever the system picks.
const FONT_FALLBACK = 'Noto Sans Math';
const fontStr = o => `${o.style || 'normal'} ${o.weight || 400} ${o.size}px "${famOf(o.font)}", "${FONT_FALLBACK}"`;
function applyFont(c, o) {
  c.font = fontStr(o); c.letterSpacing = `${(o.track || 0) * o.size}px`; c.fontStretch = o.stretch || 'normal'; c.fontKerning = 'normal';
}
const _mcache = new Map();
// Advance width (w, trailing letter-spacing removed) and ink extents of a string in font options o.
function measure(str, o) {
  const key = fontStr(o) + '|' + (o.track || 0) + '|' + (o.stretch || '') + '|' + str;
  let m = _mcache.get(key);
  if (!m) {
    applyFont(MEAS, o); MEAS.textAlign = 'left'; MEAS.textBaseline = 'alphabetic';
    const r = MEAS.measureText(str);
    m = { w: r.width - (str.length ? (o.track || 0) * o.size : 0), l: r.actualBoundingBoxLeft, r: r.actualBoundingBoxRight, asc: r.actualBoundingBoxAscent, desc: r.actualBoundingBoxDescent };
    if (_mcache.size > 20000) _mcache.clear();
    _mcache.set(key, m);
  }
  return m;
}
const capH = o => measure('H', o).asc;                            // cap height in px, for vertical centring

// ---------- the 2D draw queue ----------
// Queue a Canvas2D draw function on LETTERS. Inside a camera it draws in world coordinates through that camera.
function queue2d(fn, o = {}) { LETTERS.push({ draw: fn, cam: CAM && !o.screen ? { ...CAM } : null }); }
function run2d(c, L) {
  c.save();
  if (L.cam) { c.translate(W / 2, H / 2); c.rotate(L.cam.rot); c.scale(L.cam.zoom, L.cam.zoom); c.translate(-L.cam.cx, -L.cam.cy); }
  L.draw(c);
  c.restore();
}

// ---------- the text registry (what textCheck() inspects) ----------
// role: 'lyric' (sung words on screen), 'label' (must be readable: captions, card titles, chart labels, tweets),
//       'fine' (small print that rewards a pause: paper abstracts, citations), 'deco' (texture; never checked).
let TEXTREG = [];
function register(c, str, x0, y0, x1, y1, o) {
  const T = c.getTransform(), pts = [[x0, y0], [x1, y0], [x0, y1], [x1, y1]].map(([a, b]) => [T.a * a + T.c * b + T.e, T.b * a + T.d * b + T.f]);
  const xs = pts.map(p => p[0]), ys = pts.map(p => p[1]);
  TEXTREG.push({ s: str, role: o.role || 'label', id: o.id || null, fam: famOf(o.font), size: o.size * Math.hypot(T.a, T.b), alpha: c.globalAlpha,
    bb: [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)], col: o.color, bg: o.bg ? o.bg.col : null,
    stroke: o.stroke && (o.sw ?? o.size * .12) >= o.size * .08 ? o.stroke : null });
}

// ---------- text ----------
// tx(str, x, y, o): one run of text. Returns the font size actually used (after maxW shrink-to-fit).
//   font (FONT key or family), size, weight, style ('italic'), stretch ('condensed'...), track (letter-spacing, em)
//   color, alpha, align ('left'|'center'|'right'), base ('alphabetic'|'middle'|'top'|'bottom'), upper
//   rot, skew, sx, sy (scale about the anchor), maxW (shrink to fit)
//   stroke + sw (outline; strokeOnly for hollow text), shadow: [dx, dy, col] (hard offset shadow)
//   plates: [[dx, dy, col, alpha], ...] misregistered colour plates drawn under the main ink (riso / screenprint)
//   bg: { col, pad: [px, py], r, alpha } a box behind the text (captions, highlight bars)
//   reveal: 0..1 wipe-on from the left (revealDir: 'up' wipes from the bottom)
//   glyph: (i, ch, n) => { dx, dy, rot, s, a, col } per-character animation (drawn glyph by glyph)
//   role, id: for the checker (see TEXTREG)
function tx(str, x, y, o = {}) {
  o = { size: 64, color: PAL.ink, align: 'center', base: 'alphabetic', ...o };
  str = String(str); if (o.upper) str = str.toUpperCase();
  if (o.maxW) { const w = measure(str, o).w; if (w > o.maxW) o.size *= o.maxW / w; }
  queue2d(c => drawText(c, str, x, y, o), o);
  return o.size;
}
function drawText(c, str, x, y, o) {
  const m = measure(str, o), size = o.size;
  c.save(); c.translate(x, y); if (o.rot) c.rotate(o.rot); if (o.skew) c.transform(1, 0, o.skew, 1, 0, 0);
  if (o.sx != null || o.sy != null) c.scale(o.sx ?? 1, o.sy ?? 1);
  c.globalAlpha *= clamp(o.alpha ?? 1);
  applyFont(c, o); c.textAlign = 'left'; c.textBaseline = 'alphabetic';
  // anchor: x by align on the advance width; y by base on the cap height (so 'middle' centres capitals visually)
  const ax = o.align === 'center' ? -m.w / 2 : o.align === 'right' ? -m.w : 0, ch = capH(o);
  const ay = o.base === 'middle' ? ch / 2 : o.base === 'top' ? ch : o.base === 'bottom' ? -m.desc : 0;
  c.translate(ax, ay);
  const x0 = -m.l, x1 = m.r, y0 = -Math.max(m.asc, ch), y1 = m.desc;
  if (o.bg) {
    const [px, py] = o.bg.pad || [size * .25, size * .18], r = o.bg.r ?? 0;
    c.save(); c.globalAlpha *= o.bg.alpha ?? 1; c.fillStyle = o.bg.col; c.beginPath();
    c.roundRect(x0 - px, -ch - py, x1 - x0 + 2 * px, ch + 2 * py + (o.bg.desc ? m.desc : 0), r); c.fill(); c.restore();
  }
  if (o.reveal != null && o.reveal < 1) {
    const k = clamp(o.reveal), pad = size; c.beginPath();
    if (o.revealDir === 'up') c.rect(x0 - pad, y1 + pad - (y1 - y0 + 2 * pad) * k, x1 - x0 + 2 * pad, (y1 - y0 + 2 * pad) * k);
    else c.rect(x0 - pad, y0 - pad, (x1 - x0 + 2 * pad) * k, y1 - y0 + 2 * pad);
    c.clip();
  }
  const ink = (dx, dy, fill, strokeCol) => {
    if (o.glyph) return drawGlyphs(c, str, dx, dy, o, fill, strokeCol);
    if (strokeCol) { c.lineJoin = 'round'; c.miterLimit = 2; c.lineWidth = o.sw ?? size * .12; c.strokeStyle = strokeCol; c.strokeText(str, dx, dy); }
    if (fill) { c.fillStyle = fill; c.fillText(str, dx, dy); }
  };
  for (const [dx, dy, col, a = 1] of o.plates || []) { c.save(); c.globalAlpha *= a; ink(dx, dy, col, null); c.restore(); }
  if (o.shadow) ink(o.shadow[0], o.shadow[1], o.shadow[2], o.stroke ? o.shadow[2] : null);
  if (o.stroke) ink(0, 0, null, o.stroke);
  if (!o.strokeOnly) ink(0, 0, o.color, null);
  if (!o.noReg && (o.reveal == null || o.reveal > .5)) register(c, str, x0, y0, x1, y1, o);
  c.restore();
}
function drawGlyphs(c, str, dx, dy, o, fill, strokeCol) {
  const n = str.length;
  for (let i = 0; i < n; i++) {
    const ch = str[i]; if (ch === ' ') continue;
    const px = measure(str.slice(0, i), o).w + (i ? (o.track || 0) * o.size : 0), g = o.glyph(i, ch, n) || {}, gw = measure(ch, o).w;
    c.save(); c.translate(dx + px + gw / 2 + (g.dx || 0), dy + (g.dy || 0)); if (g.rot) c.rotate(g.rot); if (g.s != null) c.scale(g.s, g.s);
    c.globalAlpha *= clamp(g.a ?? 1);
    if (strokeCol) { c.lineJoin = 'round'; c.lineWidth = o.sw ?? o.size * .12; c.strokeStyle = strokeCol; c.strokeText(ch, -gw / 2, 0); }
    if (fill) { c.fillStyle = g.col || fill; c.fillText(ch, -gw / 2, 0); }
    c.restore();
  }
}

// ---------- layout ----------
// Lay words out in lines no wider than maxW. Returns { size, lh, lines: [{ y, width, items: [{ i, w, x, width }] }],
// width, height }: x is from the line's left edge, y is each line's baseline from the block's top edge.
function layout(words, o, maxW) {
  const sp = measure(' ', o).w, lh = o.size * (o.lh ?? 1.08), ch = capH(o), lines = [];
  let cur = { items: [], width: 0 };
  words.forEach((w, i) => {
    const s = typeof w === 'string' ? w : w.w, ow = o.styleOf && typeof w === 'object' ? { ...o, ...o.styleOf(w) } : o;   // o.styleOf(w): a word's own style (italic is wider)
    const ww = measure(o.upper ? s.toUpperCase() : s, ow).w;
    const nx = cur.items.length ? cur.width + sp : 0;
    if (cur.items.length && (nx + ww > maxW || (typeof w === 'object' && w.br))) { lines.push(cur); cur = { items: [], width: 0 }; }
    const x = cur.items.length ? cur.width + sp : 0;
    cur.items.push({ i, w: s, x, width: ww }); cur.width = x + ww;
  });
  if (cur.items.length) lines.push(cur);
  lines.forEach((l, k) => { l.y = ch + k * lh; });
  return { size: o.size, lh, lines, width: Math.max(0, ...lines.map(l => l.width)), height: ch + (lines.length - 1) * lh + o.size * .22 };
}
// Largest size in [lo, hi] whose layout fits maxW x maxH (and at most maxLines lines).
function fitLayout(words, o, maxW, maxH, lo = 20, hi = 420, maxLines = 99) {
  let best = layout(words, { ...o, size: lo }, maxW);
  for (let k = 0; k < 12; k++) {
    const mid = (lo + hi) / 2, L = layout(words, { ...o, size: mid }, maxW);
    const longest = Math.max(...words.map(w => measure(typeof w === 'string' ? w : w.w, { ...o, size: mid, ...(o.styleOf && typeof w === 'object' ? o.styleOf(w) : {}) }).w));
    if (L.height <= maxH && L.lines.length <= maxLines && longest <= maxW) { best = L; lo = mid; } else hi = mid;
  }
  return best;
}

// ---------- lyrics ----------
// lyric(line, t, o): draw a SONG line with per-word timing, fitted into a box.
//   box: [x, y, w, h] (default: centre two-thirds of the frame); align: 'left'|'center'|'right'; valign: 'top'|'middle'|'bottom'
//   mode: 'build'   each word appears on its onset (the default)
//         'karaoke' the whole line is visible; sung words take o.on, the current word fills left to right, unsung take o.pre
//         'hold'    the whole line, no per-word timing
//   enter(age, i) -> { dy, s, a, rot, col }: per-word arrival animation for 'build' (default: a quick pop up from below)
//   size: fixed size (else fitted to the box, capped by maxSize); plus any tx() style option (font, color, stroke...)
//   Words may carry {br: true} in `words` to force a line break; o.words overrides the line's display words.
// Returns the layout (for placing things around the text).
function lyric(line, t, o = {}) {
  if (!line) return null;
  const words = o.words || line.words, [bx, by, bw, bh] = o.box || [W / 6, H / 3, W * 2 / 3, H / 3];
  const st = { font: 'archivoBlack', color: PAL.ink, role: 'lyric', ...o, align: 'left', base: 'alphabetic' };
  delete st.box; delete st.words;
  const L = o.size ? layout(words, st, bw) : fitLayout(words, st, bw, bh, 20, o.maxSize || 200, o.maxLines || 99);
  st.size = L.size;
  const oy = o.valign === 'top' ? by : o.valign === 'bottom' ? by + bh - L.height : by + (bh - L.height) / 2;
  const mode = o.mode || 'build', enter = o.enter || ((age) => ({ dy: 18 * (1 - easeOut(age / .12)), s: .85 + .15 * backOut(age / .14), a: clamp(age / .05) }));
  for (const ln of L.lines) {
    const ox = o.align === 'left' ? bx : o.align === 'right' ? bx + bw - ln.width : bx + (bw - ln.width) / 2;
    for (const it of ln.items) {
      // build pops are "hits" and keep the render lead (land 0-1 frame early); the karaoke sweep must never run ahead of
      // the voice, so it undoes the lead (PROJECT.lead, see config.js)
      const w = words[it.i], x = ox + it.x + it.width / 2, y = oy + ln.y, t0 = w.t0 ?? line.t0 ?? 0, t1 = w.t1 ?? t0 + .2;
      const age = (mode === 'karaoke' ? t - (PROJECT.lead || 0) : t) - t0;
      if (mode === 'build') {
        if (age < 0) continue;
        const e = enter(age, it.i) || {};
        tx(it.w, x, y + (e.dy || 0), { ...st, align: 'center', color: e.col || st.color, sx: e.s ?? 1, sy: e.s ?? 1, rot: e.rot || 0, alpha: (st.alpha ?? 1) * (e.a ?? 1) });
      } else if (mode === 'karaoke') {
        // the dim unsung copy is what the checker sees until the fill passes half the word (then the fill is)
        const pre = o.pre || mixCol(st.color, PAL.paper, .42), on = o.on || st.color, k = age > 0 ? clamp(age / Math.max(.08, t1 - t0)) : 0;
        tx(it.w, x, y, { ...st, align: 'center', color: pre, noReg: k > .5 });
        if (k > 0) tx(it.w, x, y, { ...st, align: 'center', color: on, reveal: k });
      } else tx(it.w, x, y, { ...st, align: 'center' });
    }
  }
  return { ...L, x: bx, y: oy };
}

// ---------- crisp 2D graphics (HUD, cards, charts, profile cards) ----------
// box2d(x, y, w, h, o): fill / stroke / radius r / alpha / rot (about the centre) / dash [a, b] / shadow [dx, dy, col]
function box2d(x, y, w, h, o = {}) {
  queue2d(c => {
    c.save(); c.globalAlpha *= clamp(o.alpha ?? 1);
    if (o.rot) { c.translate(x + w / 2, y + h / 2); c.rotate(o.rot); c.translate(-x - w / 2, -y - h / 2); }
    const path = (dx = 0, dy = 0) => { c.beginPath(); c.roundRect(x + dx, y + dy, w, h, o.r || 0); };
    if (o.shadow) { path(o.shadow[0], o.shadow[1]); c.fillStyle = o.shadow[2]; c.fill(); }
    if (o.fill) { path(); c.fillStyle = o.fill; c.fill(); }
    if (o.stroke) { path(); c.lineWidth = o.sw || 3; c.strokeStyle = o.stroke; if (o.dash) c.setLineDash(o.dash); c.stroke(); }
    c.restore();
  }, o);
}
// line2d(pts, o): polyline; col, sw, dash, cap, alpha, close, fill
function line2d(pts, o = {}) {
  queue2d(c => {
    if (pts.length < 2) return;
    c.save(); c.globalAlpha *= clamp(o.alpha ?? 1); c.lineWidth = o.sw || 3; c.strokeStyle = o.col || PAL.ink; c.lineCap = o.cap || 'round'; c.lineJoin = 'round';
    if (o.dash) c.setLineDash(o.dash);
    c.beginPath(); c.moveTo(pts[0][0], pts[0][1]); for (let i = 1; i < pts.length; i++) c.lineTo(pts[i][0], pts[i][1]);
    if (o.close) c.closePath();
    if (o.fill) { c.fillStyle = o.fill; c.fill(); }
    if (o.sw !== 0) c.stroke();
    c.restore();
  }, o);
}
function dot2d(x, y, r, o = {}) {
  queue2d(c => { c.save(); c.globalAlpha *= clamp(o.alpha ?? 1); c.beginPath(); c.arc(x, y, r, 0, TAU); if (o.fill !== null) { c.fillStyle = o.fill || PAL.ink; c.fill(); } if (o.stroke) { c.lineWidth = o.sw || 2; c.strokeStyle = o.stroke; c.stroke(); } c.restore(); }, o);
}

// ---------- checks (run by: node render.mjs --textcheck=a:b [--step=.25]) ----------
const SAFE = { x0: W * .05, y0: H * .05, x1: W * .95, y1: H * .95 };   // title-safe: 90% of the frame
const MIN_SIZE = { lyric: 40, label: 26, fine: 0 };                    // font px at 1080p
const lum = hex => { const v = parseInt(hex.slice(1, 7), 16), ch = s => { s /= 255; return s <= .03928 ? s / 12.92 : ((s + .055) / 1.055) ** 2.4; }; return .2126 * ch(v >> 16 & 255) + .7152 * ch(v >> 8 & 255) + .0722 * ch(v & 255); };
const contrast = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + .05) / (y + .05); };
const toHex = (r, g, b) => '#' + [r, g, b].map(v => Math.round(v).toString(16).padStart(2, '0')).join('');
// Background colour behind a text: the median colour of a ring just outside its box (pad = a quarter of the font size),
// so the glyphs' own ink and anti-aliased edges never count as background. No colour-based exclusion: a background close
// to the text colour IS the failure we are looking for (neighbouring glyphs in the ring are outvoted by the median).
function bgBehind(bb, col, size) {
  const pad = Math.max(6, size * .25), X0 = Math.round(clamp(bb[0] - pad, 0, W - 1)), Y0 = Math.round(clamp(bb[1] - pad, 0, H - 1));
  const X1 = Math.round(clamp(bb[2] + pad, 1, W)), Y1 = Math.round(clamp(bb[3] + pad, 1, H));
  if (X1 - X0 < 2 || Y1 - Y0 < 2) return null;
  const d = outX.getImageData(X0, Y0, X1 - X0, Y1 - Y0).data, w = X1 - X0;
  const L = [], step = Math.max(1, Math.floor(Math.sqrt(d.length / 4 / 6000)));
  for (let yy = 0; yy < Y1 - Y0; yy += step) for (let xx = 0; xx < w; xx += step) {
    const x = X0 + xx, y = Y0 + yy; if (x >= bb[0] && x <= bb[2] && y >= bb[1] && y <= bb[3]) continue;   // ring only
    const i = (yy * w + xx) * 4; L.push([lum(toHex(d[i], d[i + 1], d[i + 2])), d[i], d[i + 1], d[i + 2]]);
  }
  if (L.length < 10) return null;
  L.sort((a, b) => a[0] - b[0]); const m = L[L.length >> 1]; return toHex(m[1], m[2], m[3]);
}
// Characters of str that would NOT render in the chosen face. Measured against Adobe Blank, whose every glyph is zero-
// width: a character a font lacks falls through to it and measures 0. (Comparing generic fallbacks instead misses CJK,
// where monospace, serif and fantasy all resolve to the same system font.) Symbols may come from the deliberate
// fallback (FONT_FALLBACK); letters and digits may not, since a letter from another face mid-word is a visible defect.
const _glyphCache = new Map();
function covered(ch, stack) {
  const key = stack + '|' + ch;
  if (!_glyphCache.has(key)) { MEAS.letterSpacing = '0px'; MEAS.font = `100px ${stack}, "Adobe Blank"`; _glyphCache.set(key, MEAS.measureText(ch).width > .01); }
  return _glyphCache.get(key);
}
function missingGlyphs(str, fam) {
  const out = [];
  for (const ch of new Set(str.replace(/\s/g, ''))) {
    const own = covered(ch, `"${fam}"`), viaFallback = covered(ch, `"${fam}", "${FONT_FALLBACK}"`);
    if (!viaFallback || (!own && /[\p{L}\p{N}]/u.test(ch))) out.push(ch);
  }
  return out;
}
window.renderOnly = async t => { T = t; await redraw(); composite(t); };
window.textCheck = async (a, b, step = .25) => {
  const issues = { overlap: [], unsafe: [], small: [], lowContrast: [], glyphs: [] }, seen = new Map(), glyphSeen = new Set(); let frames = 0;
  for (let t = a; t <= b + 1e-6; t += step) {
    await window.renderOnly(t); frames++;
    const R = TEXTREG.filter(r => r.role !== 'deco' && r.alpha >= .35), tt = +t.toFixed(2);
    for (const r of TEXTREG) {   // glyph coverage applies to every string, deco included
      const k = r.fam + '|' + r.s; if (glyphSeen.has(k)) continue; glyphSeen.add(k);
      const miss = missingGlyphs(r.s, r.fam); if (miss.length) issues.glyphs.push({ t: tt, s: r.s, font: r.fam, missing: miss.join('') });
    }
    for (let i = 0; i < R.length; i++) {
      const A = R[i];
      const k = A.role + '|' + (A.id ? '#' + A.id : A.s); if (!seen.has(k)) seen.set(k, { ts: [], s: A.s }); const e = seen.get(k); e.ts.push(tt); if (A.s.length > e.s.length) e.s = A.s;
      if (A.role !== 'fine' && (A.bb[0] < SAFE.x0 || A.bb[1] < SAFE.y0 || A.bb[2] > SAFE.x1 || A.bb[3] > SAFE.y1)) issues.unsafe.push({ t: tt, s: A.s, bb: A.bb.map(Math.round) });
      if (A.size < (MIN_SIZE[A.role] ?? 26)) issues.small.push({ t: tt, s: A.s, role: A.role, size: Math.round(A.size) });
      if (A.col && A.col[0] === '#') {
        const bg = A.bg || A.stroke || bgBehind(A.bb, A.col, A.size), cr = bg ? contrast(A.col, bg) : 99;
        if (cr < (A.role === 'fine' ? 2 : 3)) issues.lowContrast.push({ t: tt, s: A.s, col: A.col, bg, ratio: +cr.toFixed(2) });
      }
      for (let j = i + 1; j < R.length; j++) {
        const B = R[j]; if (A.s === B.s && A.id === B.id) continue;
        const ow = Math.min(A.bb[2], B.bb[2]) - Math.max(A.bb[0], B.bb[0]), oh = Math.min(A.bb[3], B.bb[3]) - Math.max(A.bb[1], B.bb[1]);
        if (ow <= 2 || oh <= 2) continue;
        const area = r => (r.bb[2] - r.bb[0]) * (r.bb[3] - r.bb[1]), f = ow * oh / Math.min(area(A), area(B));
        if (f > .08) issues.overlap.push({ t: tt, a: A.s, b: B.s, f: +f.toFixed(2) });
      }
    }
  }
  // reads: how long each distinct label stays up vs how long it takes to read (~3.5 words/s + 0.3 s to find it)
  const fast = [];
  for (const [k, { ts, s }] of seen) {
    const role = k.slice(0, k.indexOf('|'));
    if (role !== 'label') continue;
    let run = [ts[0], ts[0]];
    const runs = []; for (let i = 1; i < ts.length; i++) { if (ts[i] - run[1] <= step * 1.5) run[1] = ts[i]; else { runs.push(run); run = [ts[i], ts[i]]; } } runs.push(run);
    const need = s.split(/\s+/).length / 3.5 + .3, longest = Math.max(...runs.map(r => r[1] - r[0] + step));
    if (longest < need) fast.push({ s, shown: +longest.toFixed(2), need: +need.toFixed(2), at: runs[0][0] });
  }
  return { frames, step, issues, fastReads: fast };
};
