"""Extract the compact data the video's figure components need: data/figures/*.json -> video/kit/src/data/figures.js.

Usage: python tools/figures_js.py

Deliberately NOT exported (so they can never reach the screen by accident):
  * refusal prompt texts (real harmful requests from public benchmarks; the dots alone are safe)
  * induction example token strings (odd random GPT-2 fragments; review before showing any)
Every figure keeps its honest on-screen claim (`claim`) and credit line (`credit`), taken from data/figures/README.md.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D = ROOT / "data/figures"


def r(x, n=3):
    if isinstance(x, list):
        return [r(v, n) for v in x]
    return round(x, n) if isinstance(x, float) else x


def main():
    g = json.loads((D / "grokking.json").read_text())
    k1 = next(c for c in g["embedding_circles"]["circles"] if c["freq"] == 1)
    grok = {
        "claim": "Real data: a 1-layer transformer we trained on addition mod 113 (seed 0)",
        "credit": "after Nanda et al. 2023, Progress measures for grokking",
        "p": g["p"], "summary": {k: g["summary"][k] for k in ("train_acc_first_100pct_step", "test_acc_first_ge_50pct_step",
                                                             "test_acc_first_ge_99pct_step", "key_frequencies")},
        "curves": {k: r(v, 5) for k, v in g["curves"].items()},
        "fourier": {"freqs": g["embedding_fourier"]["freqs"],
                    "steps": [c["step"] for c in g["embedding_fourier"]["checkpoints"]],
                    "norms": [r(c["norms"], 3) for c in g["embedding_fourier"]["checkpoints"]]},
        "clock": {"freq": 1, "steps": [f["step"] for f in k1["frames"]], "xy": [r(f["xy"], 3) for f in k1["frames"]]},
    }
    s = json.loads((D / "superposition.json").read_text())

    def run(regime, seed=0):
        x = next(u for u in s["runs"] if u["regime"] == regime and u["seed"] == seed)
        return {"regime": regime, "p": x["feature_prob"], "importance": r(x["importance"]), "shape": x["final"]["shape"],
                "frames": [r(f["W_cols"], 3) for f in x["frames"]]}
    sup = {
        "claim": "Real data: a toy model we trained; 5 features, 2 dimensions",
        "credit": "after Elhage et al. 2022, Toy Models of Superposition",
        "steps": s["snapshot_steps"], "sparse": run("sparse_p0.05_importance_0.9^i"), "dense": run("dense_p1.0_importance_0.9^i"),
    }
    i = json.loads((D / "induction.json").read_text())
    ind = {
        "claim": "Real attention pattern from GPT-2 small, head L5H5",
        "credit": "after Olsson et al. 2022, In-context learning and induction heads",
        "head": i["induction_head"]["head"], "score": r(i["induction_head"]["score"]),
        "pattern": r(i["induction_head"]["pattern"], 2),
        "prev_head": i["previous_token_head"]["head"], "prev_pattern": r(i["previous_token_head"]["pattern"], 2),
        "loss": r(i["loss"]["batch_mean"], 2), "loss_first": r(i["loss"]["mean_first_copy_nats"], 2),
        "loss_second": r(i["loss"]["mean_second_copy_nats"], 2), "top": r(i["scores"]["top_induction_heads"][:5]),
    }
    f = json.loads((D / "refusal.json").read_text())
    pts = {k: {"x": r(v["x"], 2), "y": r(v["y"], 2)} for k, v in f["points"].items()}   # no text, ever
    cc = f["causal_check_held_out"]
    ref = {
        "claim": "Real activations from Qwen2.5-1.5B-Instruct, layer 17",
        "credit": "after Arditi et al. 2024, Refusal in LMs is mediated by a single direction",
        "points": pts, "ablation_target_x": r(f["ablation_target_x"], 2), "r_norm": r(f["r_norm"], 2),
        "mean_harmful": r(f["mean_harmful_xy"], 2), "mean_harmless": r(f["mean_harmless_xy"], 2),
        "refusing": {"harmful": r(cc["harmful_baseline"]["frac_refusing"]), "harmful_ablated": r(cc["harmful_with_direction_ablated"]["frac_refusing"]),
                     "harmless": r(cc["harmless_baseline"]["frac_refusing"]), "harmless_added": r(cc["harmless_with_direction_added"]["frac_refusing"])},
    }
    L = json.loads((D / "logit_lens.json").read_text())
    lens = {
        "claim": "Real GPT-2 small, decoded layer by layer",
        "credit": "logit lens after nostalgebraist 2020; IOI prompt after Wang et al. 2022",
        "prompt": L["prompt"], "answer": L["answer"], "distractor": L["distractor"],
        "depths": [{"depth": d["depth"], "label": d["label"], "top": r(d["top"][:3]), "mary": r(d["mary"]["prob"]),
                    "john": r(d["john"]["prob"])} for d in L["final_position"]],
    }
    out = {"grok": grok, "sup": sup, "ind": ind, "ref": ref, "lens": lens}
    js = "// generated by tools/figures_js.py from data/figures/*.json: do not edit by hand\nconst FIG = " + json.dumps(out, separators=(",", ":")) + ";\n"
    dst = ROOT / "video/kit/src/data/figures.js"
    dst.write_text(js)
    assert "harmful" not in json.dumps(ref["points"]).replace('"harmful"', "").replace('"val_harmful"', ""), "text leak?"
    print(f"wrote {dst} ({len(js) / 1024:.0f} KB); lens top at depth 9: {lens['depths'][9]['top'][:1]}")


if __name__ == "__main__":
    main()
